### ISSUE TITLE
Error While Building New Web service 

### ISSUE THREAD

**Issue by udenaka** [monkey/dudac#8]
Hi,

I am getting this error when i try to build "duda-examples/001_hello_world" using dudac -w [path-to-example]([+] WebService  : build                                                    [FAILED])

 [CC]   main.o
main.c: In function ‘_duda_main’:
main.c:95:5: error: ‘router’ undeclared (first use in this function)
     router->map("/foo/", cb_foo);
     ^
main.c:95:5: note: each undeclared identifier is reported only once for each function it appears in
make: **\* [main.o] Error 1

**Comment by edsiper** [comment]
please use branch dst-1

On Wed, Nov 11, 2015 at 5:08 AM, udenaka notifications@github.com wrote:

> Hi,
> 
> I am getting this error when i try to build
> "duda-examples/001_hello_world" using dudac -w path-to-example
> 
> [CC] main.o
> main.c: In function ‘_duda_main’:
> main.c:95:5: error: ‘router’ undeclared (first use in this function)
> router->map("/foo/", cb_foo);
> ^
> main.c:95:5: note: each undeclared identifier is reported only once for
> each function it appears in
> make: **\* [main.o] Error 1
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/monkey/dudac/issues/8.

## 

Eduardo Silva
http://edsiper.linuxchile.cl
http://monkey-project.com

**Comment by udenaka** [comment]
Hi edsiper,

dudac said it by default cloning in dst-1 but duda dst-1 doesn't have router definition. only master have definition for router ( struct duda_api_router *router; line 77 in duda_objects.h)

**Comment by edsiper** [comment]
I mean, duda-examples

On Wed, Nov 11, 2015 at 11:21 PM, udenaka notifications@github.com wrote:

> Hi edsiper,
> 
> dudac said it by default cloning in dst-1 but duda dst-1 doesn't have
> router definition. only master have definition for router ( struct
> duda_api_router *router; line 77 in duda_objects.h)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/monkey/dudac/issues/8#issuecomment-156002184.

## 

Eduardo Silva
http://edsiper.linuxchile.cl
http://monkey-project.com

**Comment by udenaka** [comment]
Thanks It works -- I was using the newer ones.
